### ISSUE TITLE
Topic words?

### ISSUE THREAD

**Issue by bwang482** [weihua916/LCTM#1]
Hi Weihua, thanks for your great work!

May I ask if it is possible to output the top-N topic words for each topic?

Thanks!

**Comment by weihua916** [comment]
Hi, thanks for your question!

In LCTM, a topic is defined as a distribution over latent concepts, not over words. Therefore, we do not have topic-word distribution as the conventional topic models do.
To interpret each topic in LCTM, we can output top-N latent concepts and represent each latent concept by some nearest words in the embedding space.
